import type { User } from '../types/user.types';
import type { Post } from '../types/post.types';
import type { Comment } from '../types/comment.types';
import type { Category, Tag } from '../types/category.types';
import type { Notification } from '../types/notification.types';
import type { Announcement } from '../types/announcement.types';
import type { Report } from '../types/report.types';
import type { AuditLog } from '../types/auditlog.types';

// ── Categories ──────────────────────────────────────────────────────
export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Academic', emoji: '📚', slug: 'academic', postCount: 142, isActive: true },
  { id: 'cat-2', name: 'Social', emoji: '🎉', slug: 'social', postCount: 89, isActive: true },
  { id: 'cat-3', name: 'Career', emoji: '💼', slug: 'career', postCount: 67, isActive: true },
  { id: 'cat-4', name: 'Housing', emoji: '🏠', slug: 'housing', postCount: 44, isActive: true },
  { id: 'cat-5', name: 'Sports', emoji: '⚽', slug: 'sports', postCount: 31, isActive: true },
];

// ── Tags ─────────────────────────────────────────────────────────────
export const mockTags: Tag[] = [
  { id: 'tag-1', name: 'internship', slug: 'internship' },
  { id: 'tag-2', name: 'exams', slug: 'exams' },
  { id: 'tag-3', name: 'tips', slug: 'tips' },
  { id: 'tag-4', name: 'roommate', slug: 'roommate' },
  { id: 'tag-5', name: 'football', slug: 'football' },
  { id: 'tag-6', name: 'mental-health', slug: 'mental-health' },
  { id: 'tag-7', name: 'placement', slug: 'placement' },
  { id: 'tag-8', name: 'freshers', slug: 'freshers' },
];

// ── Users ────────────────────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: 'u-1',
    username: 'alex_campus',
    email: 'alex@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    bio: 'CS senior. Loves coffee and distributed systems.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2024-08-01T10:00:00Z',
    postCount: 23,
    commentCount: 87,
  },
  {
    id: 'u-2',
    username: 'priya_dev',
    email: 'priya@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    bio: 'ML enthusiast. Final year student.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2024-08-15T09:00:00Z',
    postCount: 11,
    commentCount: 56,
  },
  {
    id: 'u-3',
    username: 'sam_jones',
    email: 'sam@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sam',
    bio: 'Sophomore. Big into football and housing struggles.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2024-09-01T08:00:00Z',
    postCount: 5,
    commentCount: 34,
  },
  {
    id: 'u-4',
    username: 'nisha_r',
    email: 'nisha@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nisha',
    bio: 'Career counselor wannabe. Placement cell member.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2024-08-20T11:00:00Z',
    postCount: 18,
    commentCount: 102,
  },
  {
    id: 'u-5',
    username: 'raj_k',
    email: 'raj@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=raj',
    bio: 'Fresher. Still figuring it all out.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2025-01-10T14:00:00Z',
    postCount: 2,
    commentCount: 9,
  },
  {
    id: 'u-6',
    username: 'mia_writes',
    email: 'mia@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mia',
    bio: 'Literary club president. Writes about campus life.',
    role: 'STUDENT',
    status: 'SUSPENDED',
    createdAt: '2024-07-25T16:00:00Z',
    postCount: 30,
    commentCount: 200,
  },
  {
    id: 'u-7',
    username: 'kevin_wu',
    email: 'kevin@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kevin',
    bio: 'Physics nerd. Avid gamer.',
    role: 'STUDENT',
    status: 'ACTIVE',
    createdAt: '2024-09-10T10:30:00Z',
    postCount: 7,
    commentCount: 45,
  },
  {
    id: 'u-8',
    username: 'sarah_t',
    email: 'sarah@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    bio: 'Biotech. Curious about everything.',
    role: 'STUDENT',
    status: 'BANNED',
    createdAt: '2024-08-05T07:00:00Z',
    postCount: 1,
    commentCount: 4,
  },
  {
    id: 'u-9',
    username: 'mod_dave',
    email: 'dave@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=dave',
    bio: 'Campus forum moderator.',
    role: 'MODERATOR',
    status: 'ACTIVE',
    createdAt: '2024-06-01T09:00:00Z',
    postCount: 3,
    commentCount: 120,
  },
  {
    id: 'u-10',
    username: 'admin_root',
    email: 'admin@university.edu',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=root',
    bio: 'Platform administrator.',
    role: 'ADMIN',
    status: 'ACTIVE',
    createdAt: '2024-01-01T00:00:00Z',
    postCount: 0,
    commentCount: 0,
  },
];

export const mockCurrentUser = mockUsers[0]; // alex_campus is logged in

// ── Posts ─────────────────────────────────────────────────────────────
export const mockPosts: Post[] = [
  {
    id: 'post-1',
    title: 'How I landed a FAANG internship from our campus — full breakdown',
    content: `After three grueling months of preparation, I finally got the call. Here's everything I did differently.\n\nFirst, I started grinding LeetCode in January — a full 6 months before the internship season kicked off. The key wasn't doing more problems; it was doing the same 150 problems three times over until the patterns became muscle memory.\n\nSecond, I networked relentlessly on LinkedIn. I sent 200 cold messages, got 30 responses, and 5 referrals. One of those referrals led directly to the offer.\n\nFeel free to ask me anything in the comments.`,
    author: { isAnonymous: false, user: mockUsers[0] },
    category: mockCategories[2],
    tags: [mockTags[0], mockTags[6]],
    isAnonymous: false,
    isPinned: true,
    isFeatured: true,
    isLocked: false,
    viewCount: 1240,
    commentCount: 47,
    reactions: [
      { type: 'LIKE', count: 234, reacted: true },
      { type: 'LOVE', count: 89, reacted: false },
      { type: 'FUNNY', count: 12, reacted: false },
      { type: 'SAD', count: 3, reacted: false },
      { type: 'ANGRY', count: 1, reacted: false },
    ],
    createdAt: '2026-06-24T08:30:00Z',
    updatedAt: '2026-06-24T08:30:00Z',
  },
  {
    id: 'post-2',
    title: 'The dorm heating situation in Block C is getting dangerous',
    content: `I know this has been brought up before but nothing has changed. Last night the temperature in Block C dropped to 8°C inside the room. I've filed three maintenance requests — all closed without action.\n\nIf you're in the same situation, please reply so we can collectively escalate this to the student union.`,
    author: { isAnonymous: true, displayName: 'Anonymous' },
    category: mockCategories[3],
    tags: [mockTags[3]],
    isAnonymous: true,
    isPinned: false,
    isFeatured: false,
    isLocked: false,
    viewCount: 678,
    commentCount: 31,
    reactions: [
      { type: 'LIKE', count: 145, reacted: false },
      { type: 'LOVE', count: 5, reacted: false },
      { type: 'FUNNY', count: 2, reacted: false },
      { type: 'SAD', count: 67, reacted: false },
      { type: 'ANGRY', count: 89, reacted: false },
    ],
    createdAt: '2026-06-25T22:10:00Z',
    updatedAt: '2026-06-25T22:10:00Z',
  },
  {
    id: 'post-3',
    title: 'Semester exam timetable leaked — discuss here',
    content: `Someone from the registrar's office shared the provisional timetable. Exams start July 15th. CS papers are clustered — three back-to-back. Not ideal but at least we have three weeks.\n\nSee the schedule in the comments.`,
    author: { isAnonymous: false, user: mockUsers[1] },
    category: mockCategories[0],
    tags: [mockTags[1], mockTags[2]],
    isAnonymous: false,
    isPinned: false,
    isFeatured: false,
    isLocked: false,
    viewCount: 3200,
    commentCount: 112,
    reactions: [
      { type: 'LIKE', count: 412, reacted: false },
      { type: 'LOVE', count: 20, reacted: false },
      { type: 'FUNNY', count: 44, reacted: true },
      { type: 'SAD', count: 198, reacted: false },
      { type: 'ANGRY', count: 75, reacted: false },
    ],
    createdAt: '2026-06-26T07:00:00Z',
    updatedAt: '2026-06-26T07:00:00Z',
  },
  {
    id: 'post-4',
    title: 'Football trials next week — all years welcome!',
    content: `Hey everyone! The university football club is holding open trials next Tuesday at 4 PM on the main ground.\n\nAll years are welcome regardless of experience. We need defenders and a goalkeeper urgently. Show up in proper boots.`,
    author: { isAnonymous: false, user: mockUsers[2] },
    category: mockCategories[4],
    tags: [mockTags[4]],
    isAnonymous: false,
    isPinned: false,
    isFeatured: false,
    isLocked: false,
    viewCount: 420,
    commentCount: 18,
    reactions: [
      { type: 'LIKE', count: 98, reacted: false },
      { type: 'LOVE', count: 34, reacted: false },
      { type: 'FUNNY', count: 5, reacted: false },
      { type: 'SAD', count: 0, reacted: false },
      { type: 'ANGRY', count: 0, reacted: false },
    ],
    createdAt: '2026-06-25T14:00:00Z',
    updatedAt: '2026-06-25T14:00:00Z',
  },
  {
    id: 'post-5',
    title: 'Is anyone else really struggling mentally this semester?',
    content: `I don't want to use my real name for this. The pressure this semester has been overwhelming. Between projects, placement prep, and family expectations, I'm barely holding on.\n\nJust wanted to know if others feel the same way. The counseling center waitlist is 3 weeks long which feels impossible.\n\nIf you're going through this too, you're not alone.`,
    author: { isAnonymous: true, displayName: 'Anonymous' },
    category: mockCategories[1],
    tags: [mockTags[5]],
    isAnonymous: true,
    isPinned: false,
    isFeatured: false,
    isLocked: false,
    viewCount: 890,
    commentCount: 64,
    reactions: [
      { type: 'LIKE', count: 23, reacted: false },
      { type: 'LOVE', count: 312, reacted: false },
      { type: 'FUNNY', count: 1, reacted: false },
      { type: 'SAD', count: 245, reacted: false },
      { type: 'ANGRY', count: 8, reacted: false },
    ],
    createdAt: '2026-06-23T20:00:00Z',
    updatedAt: '2026-06-23T20:00:00Z',
  },
];

// ── Comments ──────────────────────────────────────────────────────────
export const mockComments: Comment[] = [
  {
    id: 'cmt-1',
    postId: 'post-1',
    content: 'This is so helpful! Which resources did you use for system design prep?',
    author: { isAnonymous: false, user: mockUsers[1] },
    isAnonymous: false,
    replyCount: 2,
    replies: [
      {
        id: 'cmt-1-1',
        postId: 'post-1',
        content: 'Grokking the System Design Interview + Alex Xu\'s book were my go-tos.',
        author: { isAnonymous: false, user: mockUsers[0] },
        isAnonymous: false,
        parentId: 'cmt-1',
        replyCount: 0,
        createdAt: '2026-06-24T09:00:00Z',
        updatedAt: '2026-06-24T09:00:00Z',
      },
      {
        id: 'cmt-1-2',
        postId: 'post-1',
        content: 'Also recommend ByteByteGo on YouTube — free and super visual.',
        author: { isAnonymous: false, user: mockUsers[3] },
        isAnonymous: false,
        parentId: 'cmt-1',
        replyCount: 0,
        createdAt: '2026-06-24T09:30:00Z',
        updatedAt: '2026-06-24T09:30:00Z',
      },
    ],
    createdAt: '2026-06-24T08:50:00Z',
    updatedAt: '2026-06-24T08:50:00Z',
  },
  {
    id: 'cmt-2',
    postId: 'post-1',
    content: 'Congrats! Was the interview all virtual or did they fly you in?',
    author: { isAnonymous: false, user: mockUsers[6] },
    isAnonymous: false,
    replyCount: 1,
    replies: [
      {
        id: 'cmt-2-1',
        postId: 'post-1',
        content: 'All virtual — 5 rounds over 2 days via video call.',
        author: { isAnonymous: false, user: mockUsers[0] },
        isAnonymous: false,
        parentId: 'cmt-2',
        replyCount: 0,
        createdAt: '2026-06-24T10:10:00Z',
        updatedAt: '2026-06-24T10:10:00Z',
      },
    ],
    createdAt: '2026-06-24T10:00:00Z',
    updatedAt: '2026-06-24T10:00:00Z',
  },
  {
    id: 'cmt-3',
    postId: 'post-1',
    content: 'Did campus placement come before or after the off-campus offer?',
    author: { isAnonymous: true, displayName: 'Anonymous' },
    isAnonymous: true,
    replyCount: 0,
    createdAt: '2026-06-24T11:00:00Z',
    updatedAt: '2026-06-24T11:00:00Z',
  },
  {
    id: 'cmt-4',
    postId: 'post-2',
    content: 'I\'m in Block C too. Filed 4 requests since October. Total silence.',
    author: { isAnonymous: false, user: mockUsers[4] },
    isAnonymous: false,
    replyCount: 0,
    createdAt: '2026-06-25T22:30:00Z',
    updatedAt: '2026-06-25T22:30:00Z',
  },
  {
    id: 'cmt-5',
    postId: 'post-2',
    content: 'The student union has a complaint form — let\'s coordinate there.',
    author: { isAnonymous: false, user: mockUsers[3] },
    isAnonymous: false,
    replyCount: 0,
    createdAt: '2026-06-25T23:00:00Z',
    updatedAt: '2026-06-25T23:00:00Z',
  },
  {
    id: 'cmt-6',
    postId: 'post-5',
    content: 'You are absolutely not alone. I\'ve been feeling the same. Hang in there 💙',
    author: { isAnonymous: false, user: mockUsers[1] },
    isAnonymous: false,
    replyCount: 0,
    createdAt: '2026-06-23T20:30:00Z',
    updatedAt: '2026-06-23T20:30:00Z',
  },
  {
    id: 'cmt-7',
    postId: 'post-5',
    content: 'The peer support WhatsApp group can be helpful while you wait for counseling. DM me.',
    author: { isAnonymous: true, displayName: 'Anonymous' },
    isAnonymous: true,
    replyCount: 0,
    createdAt: '2026-06-23T21:00:00Z',
    updatedAt: '2026-06-23T21:00:00Z',
  },
  {
    id: 'cmt-8',
    postId: 'post-5',
    content: 'Same boat. Three weeks waitlist is a joke. We need more counselors.',
    author: { isAnonymous: false, user: mockUsers[6] },
    isAnonymous: false,
    replyCount: 0,
    createdAt: '2026-06-23T21:30:00Z',
    updatedAt: '2026-06-23T21:30:00Z',
  },
];

// ── Notifications ─────────────────────────────────────────────────────
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    type: 'COMMENT_ON_POST',
    message: 'priya_dev commented on your post "How I landed a FAANG internship..."',
    isRead: false,
    targetType: 'POST',
    targetId: 'post-1',
    actorUsername: 'priya_dev',
    createdAt: '2026-06-24T08:52:00Z',
  },
  {
    id: 'notif-2',
    type: 'REACTION_ON_POST',
    message: '89 people reacted ❤️ to your post.',
    isRead: false,
    targetType: 'POST',
    targetId: 'post-1',
    createdAt: '2026-06-24T12:00:00Z',
  },
  {
    id: 'notif-3',
    type: 'REPLY_TO_COMMENT',
    message: 'nisha_r replied to your comment.',
    isRead: true,
    targetType: 'COMMENT',
    targetId: 'cmt-1',
    actorUsername: 'nisha_r',
    createdAt: '2026-06-24T09:32:00Z',
  },
  {
    id: 'notif-4',
    type: 'POST_FEATURED',
    message: 'Your post was featured by a moderator! 🎉',
    isRead: true,
    targetType: 'POST',
    targetId: 'post-1',
    createdAt: '2026-06-24T10:00:00Z',
  },
  {
    id: 'notif-5',
    type: 'ANNOUNCEMENT',
    message: 'New announcement: Mid-semester break dates confirmed.',
    isRead: false,
    createdAt: '2026-06-25T09:00:00Z',
  },
];

// ── Announcements ─────────────────────────────────────────────────────
export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: '🎓 Mid-Semester Break: July 1–5',
    body: 'The university has confirmed the mid-semester break from July 1st to July 5th. Campus facilities remain open. Library hours extended.',
    isHighlighted: true,
    isActive: true,
    expiresAt: '2026-07-05T23:59:00Z',
    createdAt: '2026-06-25T09:00:00Z',
    createdByUsername: 'admin_root',
  },
  {
    id: 'ann-2',
    title: 'Placement Cell: Registration Deadline June 30',
    body: 'Final year students must complete their placement registration by June 30. Late registrations will not be accepted.',
    isHighlighted: false,
    isActive: true,
    expiresAt: '2026-06-30T23:59:00Z',
    createdAt: '2026-06-20T10:00:00Z',
    createdByUsername: 'admin_root',
  },
  {
    id: 'ann-3',
    title: 'Forum Rules Reminder',
    body: 'Please be respectful and follow community guidelines. Any harassment or spam will result in account action.',
    isHighlighted: false,
    isActive: true,
    createdAt: '2026-06-01T08:00:00Z',
    createdByUsername: 'mod_dave',
  },
];

// ── Reports ───────────────────────────────────────────────────────────
export const mockReports: Report[] = [
  {
    id: 'rep-1',
    targetType: 'POST',
    targetId: 'post-5',
    targetPreview: 'Is anyone else really struggling mentally this semester?',
    reason: 'SELF_HARM_CONCERN',
    description: 'The post mentions "barely holding on" — concerned about poster\'s wellbeing.',
    reporter: mockUsers[3],
    status: 'PENDING',
    createdAt: '2026-06-23T21:00:00Z',
  },
  {
    id: 'rep-2',
    targetType: 'COMMENT',
    targetId: 'cmt-3',
    targetPreview: 'Did campus placement come before or after...',
    reason: 'SPAM',
    description: 'Repeated the same question in 10 different posts.',
    reporter: mockUsers[2],
    status: 'PENDING',
    createdAt: '2026-06-24T11:30:00Z',
  },
  {
    id: 'rep-3',
    targetType: 'POST',
    targetId: 'post-3',
    targetPreview: 'Semester exam timetable leaked — discuss here',
    reason: 'MISINFORMATION',
    description: 'The shared timetable is unofficial and may be inaccurate.',
    reporter: mockUsers[4],
    status: 'ACCEPTED',
    createdAt: '2026-06-26T07:30:00Z',
    resolvedAt: '2026-06-26T09:00:00Z',
    resolvedBy: mockUsers[8],
  },
  {
    id: 'rep-4',
    targetType: 'COMMENT',
    targetId: 'cmt-5',
    targetPreview: 'The student union has a complaint form...',
    reason: 'HARASSMENT',
    description: 'User repeatedly targets the same person.',
    reporter: mockUsers[6],
    status: 'REJECTED',
    createdAt: '2026-06-25T23:30:00Z',
    resolvedAt: '2026-06-26T08:00:00Z',
    resolvedBy: mockUsers[8],
  },
  {
    id: 'rep-5',
    targetType: 'POST',
    targetId: 'post-4',
    targetPreview: 'Football trials next week — all years welcome!',
    reason: 'INAPPROPRIATE_CONTENT',
    description: 'Contains off-site spam link in the body.',
    reporter: mockUsers[1],
    status: 'PENDING',
    createdAt: '2026-06-25T15:00:00Z',
  },
];

// ── Audit Logs ────────────────────────────────────────────────────────
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'al-1',
    adminUsername: 'mod_dave',
    action: 'REPORT_ACCEPTED',
    targetType: 'REPORT',
    targetId: 'rep-3',
    note: 'Timetable confirmed unverified by registrar.',
    createdAt: '2026-06-26T09:00:00Z',
  },
  {
    id: 'al-2',
    adminUsername: 'mod_dave',
    action: 'REPORT_REJECTED',
    targetType: 'REPORT',
    targetId: 'rep-4',
    note: 'No harassment found upon review.',
    createdAt: '2026-06-26T08:00:00Z',
  },
  {
    id: 'al-3',
    adminUsername: 'admin_root',
    action: 'USER_SUSPENDED',
    targetType: 'USER',
    targetId: 'u-6',
    note: 'Multiple spam reports confirmed.',
    createdAt: '2026-06-25T16:00:00Z',
  },
  {
    id: 'al-4',
    adminUsername: 'admin_root',
    action: 'POST_FEATURED',
    targetType: 'POST',
    targetId: 'post-1',
    note: 'High quality internship guide.',
    createdAt: '2026-06-24T10:00:00Z',
  },
  {
    id: 'al-5',
    adminUsername: 'admin_root',
    action: 'ANNOUNCEMENT_CREATED',
    targetType: 'ANNOUNCEMENT',
    targetId: 'ann-1',
    note: 'Mid-semester break dates announced.',
    createdAt: '2026-06-25T09:00:00Z',
  },
];
